/**
 * @license Copyright 2000-2011 ANTEE s.r.o., All rights reserved. Confidential.
 */

app.locales = $.extend(app.locales || {}, {
  lang: "cs",
  datepicker: {
    closeText: "Zavřít",
    prevText: "&#x3C;Dříve",
    nextText: "Později&#x3E;",
    currentText: "Nyní",
    monthNames: [
      "Leden",
      "Únor",
      "Březen",
      "Duben",
      "Květen",
      "Červen",
      "Červenec",
      "Srpen",
      "Září",
      "Říjen",
      "Listopad",
      "Prosinec",
    ],
    monthNamesShort: [
      "Led",
      "Úno",
      "Bře",
      "Dub",
      "Kvě",
      "Čer",
      "Čvc",
      "Srp",
      "Zář",
      "Říj",
      "Lis",
      "Pro",
    ],
    dayNames: [
      "Neděle",
      "Pondělí",
      "Úterý",
      "Středa",
      "Čtvrtek",
      "Pátek",
      "Sobota",
    ],
    dayNamesShort: ["Ned", "Pon", "Úte", "Stř", "Čtv", "Pát", "Sob"],
    dayNamesMin: ["Ne", "Po", "Út", "St", "Čt", "Pá", "So"],
    week: "týden",
    weekHeader: "Týden",
    weekFormat: "w. 'týden' yy",
    dateFormat: "dd.mm.yy",
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: "",
  },
  timepicker: {
    timeOnlyTitle: "Vyberte čas",
    timeText: "Čas",
    hourText: "Hodina",
    minuteText: "Minuta",
    secondText: "Vteřiny",
    millisecText: "Milisekundy",
    timezoneText: "Časové pásmo",
    currentText: "Nyní",
    closeText: "OK",
    timeFormat: "HH:mm",
    amNames: ["AM", "A"],
    pmNames: ["PM", "P"],
    isRTL: false,
  },
  richeditor: {
    fontSizes: {
      huge: "Velké",
      bigger: "Větší",
      normal: "Normální",
      smaller: "Menší",
      small: "Malé",
    },
    editDescription: "Upravit popis",
    insertDescription: "Vložit popis",
    titleCreate: "Vložit odstavec",
    titleEdit: "Upravit odstavec",
    templates: {
      subPagesList: "Výpis přímých podstránek",
      subPagesListDesc:
        "Widget vypisující seznam přímých podstránek této stránky.",
    },
  },
  characterCounter: {
    characterCounter: "Počet zbývajících znaků: ",
    reachedLimit: "Přesáhli jste limit pro úvodní text.",
    surplusesCounter: "Počet přebývajících znaků: ",
  },
  characterCounterSMS: {
    reachedLimit: "Přesáhli jste limit pro SMS zprávu.",
    countMessages: "Počet SMS:",
    countCharSMS: "znaků zbývá do navýšení počtu SMS",
  },
  confirm: "Jste si jisti?",
  yes: "Ano",
  no: "Ne",
  insertItem: "Vložit položku",
  editItem: "Upravit položku",
  edit: "Upravit",
  save: "Uložit",
  close: "Zavřít",
  loading: "Nahrávají se data...",
  preventDiscardChanges: "Změny nebudou uloženy. Chcete pokračovat?",
  deleteConfirm: "Opravdu si přejete smazat vybranou položku?",
  originalValue: "Původní hodnota: ",
  newValue: "Nová hodnota: ",
  "Default color": "Výchozí barva",
  copied: "Zkopírováno",
  highlightPageType: "Zvýraznit typ stránky...",
  searchInPageTitle: "Vyhledat podle názvu stránky...",
  Found: "Nalezeno",
});
